### ISSUE TITLE
Tabs. Or. Spaces.

### ISSUE THREAD

**Issue by ethhics** [zmscott5/CSCE-121-Team-22#6]
I like 4 spaces. I also like tabs. I see the benefits and issues with each. But the important thing is that our code should look like it was all written by the same person, and to do that we need to standardize.

**Comment by ethhics** [comment]
Michael likes tabs. What's your preference @rangel904?

**Comment by rangel904** [comment]
i usually use tabs,

**Comment by ethhics** [comment]
Tabs will be used for indentation.
